[package]
name = "dockable_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
csv = "1.3.1"
eframe = "0.31.0"
egui = "0.31.0"
log = "0.4.26"
rdev = "0.5.3"
simple_logger = "5.0.0"